name: Makefile CI

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        libgtk: [libgtk-3-dev, libgtk2.0-dev]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: "Install requirements"
      run: sudo apt-get install gtk-doc-tools docbook-xsl yelp-tools libpng-dev ${{ matrix.libgtk }} libicu-dev libjson-glib-dev intltool autopoint xxd libcurl4-gnutls-dev libglib2.0-dev-bin libsqlite3-dev nettle-dev libmapnik-dev libgeoclue-2-dev libgexiv2-dev libgps-dev libmagic-dev libbz2-dev libzip-dev liboauth-dev libnova-dev
      shell: bash

    - name: Configure
      run: ./autogen.sh ${{ matrix.libgtk == 'libgtk2.0-dev' && '--enable-gtk2' || '' }}
      
    - name: Build
      run: make

    - name: Run check
      uses: coactions/setup-xvfb@v1
      with:
        run: make check

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test-suite-log-${{ matrix.os }}-${{ matrix.libgtk }}
        path: test/test-suite.log
        retention-days: 5

    - name: Run distcheck
      run: make distcheck DISTCHECK_CONFIGURE_FLAGS=${{ matrix.libgtk == 'libgtk2.0-dev' && '--enable-gtk2' || '' }}
