name: CI Build Variants

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        #             v----------------------- Optional library components -----------------------------------------v  v----------------code features -----------------v
        no-variants: [bzip2, geoclue, geotag, magic, mapnik, mbtiles, nova, nettle, oauth, realtime-gps-tracking, zip, bing, google, bluemarble, geonames, openstreetmap]

# NB specifically limited to single OS variant and default GTK, in order to keep number of runs within reason
# Thus much more likely to keep within overall compute quota limits for a given time period
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

# See at least https://github.com/actions/runner-images/issues/2155
#  regarding ubuntu default image vs server packages mismatch
# Hence must always *update* before applying any install
    - name: "Install requirements"
      run: sudo apt-get update -y && sudo apt-get install gtk-doc-tools docbook-xsl yelp-tools libpng-dev libgtk-3-dev libicu-dev libjson-glib-dev intltool autopoint xxd libcurl4-gnutls-dev libglib2.0-dev-bin libsqlite3-dev nettle-dev libmapnik-dev libgeoclue-2-dev libgexiv2-dev libgps-dev libmagic-dev libbz2-dev libzip-dev liboauth-dev libnova-dev
      shell: bash

# Should work without the optional library component being installed - but ATM not going bother (de)configuring the OS
    - name: Build Options
      run: ./autogen.sh --disable-${{ matrix.no-variants }} && make

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-suite-disabled-${{ matrix.no-variants }}.log
        path: test/test-suite.log
        retention-days: 7

